### ISSUE TITLE
No info for some tickets

### ISSUE THREAD

**Issue by Ramazik** [asdcorp/WindowsRentFree#1]
Hello! Great work ))
But no info in keys.md about:

KMS.xml
Microsoft.Windows.125.X22-66075_8wekyb3d8bbwe.xml
Microsoft.Windows.126.X22-66108_8wekyb3d8bbwe.xml

**Comment by ave9858** [comment]
KMS.xml is for kms38 activation. Those other two tickets are for editions that can't normally be activated with HWID, so there is no key to install.
