### ISSUE TITLE
No genuine ticket for ServerRdsh/Enterprise multi-session?

### ISSUE THREAD

**Issue by pivotman319-owo** [asdcorp/WindowsRentFree#2]
Title. ServerRdsh (Enterprise multi-session/Server Remote Desktop Session Host) is basically just a variant virtual edition for Professional/Enterprise but optimized for Azure VMs. Generic product key is NJCF7-PW8QT-3324D-688JX-2YV66.

I wonder why there's no genuine ticket for it here?

**Comment by ave9858** [comment]
It doesn't need a genuine ticket to be activated, just inserting the key is enough to activate it, although activation isn't officially supported outside of azure and you really shouldn't be using it.

**Comment by pivotman319-owo** [comment]
gotcha, thanks. closing this issue then
